<Project>
  <PropertyGroup>
    <RevitYear Condition="'$(RevitYear)' == ''">2026</RevitYear>
    <TargetFramework Condition="'$(RevitYear)' != '2027'">net8.0-windows</TargetFramework>
    <TargetFramework Condition="'$(RevitYear)' == '2027'">net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)version.txt').Trim())</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>portable</DebugType>
  </PropertyGroup>
</Project>
